// sveltekit-temp/src/lib/components/user-avatar.svelte
<script lang="ts">
import { Avatar, AvatarFallback, AvatarImage } from "$lib/components/ui/avatar"

interface Props {
  name: string
  imageUrl?: string | null
  size?: "default" | "sm" | "lg"
  class?: string
  fallbackClassName?: string
}

let {
  name,
  imageUrl = null,
  size = "default",
  class: className = "",
  fallbackClassName = ""
}: Props = $props()

function getUserInitials(name: string) {
  const initials = name
    .trim()
    .split(/\s+/)
    .slice(0, 2)
    .map((part) => part[0])
    .join("")
    .toUpperCase()

  return initials || "?"
}
</script>

<Avatar class={className}>
  {#if imageUrl}
    <AvatarImage src={imageUrl} alt={name} />
  {/if}
  <AvatarFallback class={fallbackClassName}>
    {getUserInitials(name)}
  </AvatarFallback>
</Avatar>

// components/user-avatar.tsx
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar"

export interface UserAvatarProps {
  name: string
  imageUrl?: string | null
  size?: "default" | "sm" | "lg"
  className?: string
  fallbackClassName?: string
}

export function getUserInitials(name: string) {
  const initials = name
    .trim()
    .split(/\s+/)
    .slice(0, 2)
    .map((part) => part[0])
    .join("")
    .toUpperCase()

  return initials || "?"
}

export function UserAvatar({
  name,
  imageUrl,
  size = "default",
  className,
  fallbackClassName
}: UserAvatarProps) {
  return (
    <Avatar className={className} size={size}>
      {imageUrl ? <AvatarImage src={imageUrl} alt={name} /> : null}
      <AvatarFallback className={fallbackClassName}>
        {getUserInitials(name)}
      </AvatarFallback>
    </Avatar>
  )
}
