// sveltekit-temp/src/routes/(dashboard)/admin/administration/users/+page.svelte
<script lang="ts">
import AdministrationListPage from "$lib/components/administration/administration-list-page.svelte"
import DashboardShell from "$lib/components/tradexpo/dashboard-shell.svelte"
import type { PageData } from "./$types"

interface Props {
  data: PageData
}

let { data }: Props = $props()
</script>

<DashboardShell
  title="Users"
  breadcrumbs={[
    { label: "Dashboard", href: "/admin" },
    { label: "Administration" },
    { label: "Users" }
  ]}
>
  <AdministrationListPage entity="users" initialData={data.initialData} />
</DashboardShell>

// app/(dashboard)/admin/administration/users/page.tsx
import { AdministrationListPage } from "@/components/administration/administration-list-page"
import { DashboardShell } from "@/components/tradexpo/dashboard-shell"
import { getAdministrationList } from "@/lib/administration/list"
import { ensurePlatformSchema } from "@/lib/platform/ensure-schema"

export const dynamic = "force-dynamic"

export default async function AdminUsersPage() {
  await ensurePlatformSchema()
  const initialData = await getAdministrationList({
    entity: "users",
    pageSize: 20
  })

  return (
    <DashboardShell
      title="Users"
      breadcrumbs={[
        { label: "Dashboard", href: "/admin" },
        { label: "Administration" },
        { label: "Users" }
      ]}
    >
      <AdministrationListPage entity="users" initialData={initialData} />
    </DashboardShell>
  )
}
