// components/landing/user-menu.tsx
"use client"

import {
  BellIcon,
  CogIcon,
  HeartIcon,
  LayoutDashboard,
  ListChecksIcon,
  MessageCircleMoreIcon,
  User
} from "lucide-react"
import Link from "next/link"
import { useRouter } from "next/navigation"
import { Button } from "@/components/ui/button"
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuLabel,
  DropdownMenuSeparator,
  DropdownMenuTrigger
} from "@/components/ui/dropdown-menu"
import { UserAvatar } from "@/components/user-avatar"

interface UserMenuProps {
  user: {
    id: string
    name: string
    email: string
    roles: string[]
  }
}

export function UserMenu({ user }: UserMenuProps) {
  const router = useRouter()

  const handleLogout = async () => {
    await fetch("/api/auth/logout", { method: "POST" })
    router.refresh()
  }

  const getDashboardPath = () => {
    if (user.roles.includes("admin")) return "/admin"
    if (user.roles.includes("partner")) return "/partner"
    return "/seller"
  }

  const getNotificationPath = () => {
    if (user.roles.includes("admin")) return "/admin/notifications"
    if (user.roles.includes("partner")) return "/partner/notifications"
    return "/seller/notifications"
  }

  return (
    <DropdownMenu>
      <DropdownMenuTrigger asChild>
        <Button variant="ghost" className="relative h-10 w-10 rounded-full p-0">
          <UserAvatar
            name={user.name}
            imageUrl="/avatar.webp"
            className="h-10 w-10"
          />
        </Button>
      </DropdownMenuTrigger>
      <DropdownMenuContent
        className="w-64 rounded-2xl px-0 py-3"
        align="end"
        forceMount
      >
        <DropdownMenuItem asChild className="gap-2 rounded-none px-4 py-2.25">
          <Link href={getNotificationPath()}>
            <BellIcon strokeWidth="2" />
            <span className="font-medium">Notifications</span>
          </Link>
        </DropdownMenuItem>
        {!user.roles.includes("admin") && (
          <>
            <DropdownMenuItem
              asChild
              className="gap-2 rounded-none px-4 py-2.25"
            >
              <Link href="/seller/deal-room">
                <MessageCircleMoreIcon strokeWidth="2" />
                <span className="font-medium">Deal Room</span>
              </Link>
            </DropdownMenuItem>
            <DropdownMenuItem
              asChild
              className="gap-2 rounded-none px-4 py-2.25"
            >
              <Link href="/seller/deal-room">
                <ListChecksIcon strokeWidth="2" />
                <span className="font-medium">RFQ Hub</span>
              </Link>
            </DropdownMenuItem>
            <DropdownMenuItem
              asChild
              className="gap-2 rounded-none px-4 py-2.25"
            >
              <Link href="/seller/deal-room">
                <HeartIcon strokeWidth="2" />
                <span className="font-medium">Wishlist</span>
              </Link>
            </DropdownMenuItem>
            <DropdownMenuItem
              asChild
              className="gap-2 rounded-none px-4 py-2.25"
            >
              <Link href="/profile">
                <User strokeWidth="2" />
                <span className="font-medium">Profile</span>
              </Link>
            </DropdownMenuItem>
          </>
        )}

        {/* User Workspace */}

        {/* Partner Portal */}
        {user.roles.includes("partner") && (
          <>
            <DropdownMenuSeparator />
            <DropdownMenuLabel className="pl-4">Portal</DropdownMenuLabel>
            <DropdownMenuItem
              className="gap-2 rounded-none px-4 py-2.25"
              asChild
            >
              <Link href={getDashboardPath()}>
                <LayoutDashboard strokeWidth="2" />
                <span className="font-medium">Dashboard</span>
              </Link>
            </DropdownMenuItem>

            <DropdownMenuItem
              className="gap-2 rounded-none px-4 py-2.25"
              asChild
            >
              <Link href="/partner/settings">
                <CogIcon strokeWidth="2" />
                <span className="font-medium">Settings</span>
              </Link>
            </DropdownMenuItem>
          </>
        )}

        <DropdownMenuSeparator />
        <DropdownMenuItem
          onClick={handleLogout}
          className="gap-2 rounded-none px-4 py-2.25"
        >
          <span className="font-normal">Log out</span>
        </DropdownMenuItem>
      </DropdownMenuContent>
    </DropdownMenu>
  )
}

// sveltekit-temp/src/lib/components/landing/user-menu.svelte
<script lang="ts">
import {
  Bell,
  Heart,
  LayoutDashboard,
  ListChecks,
  MessageCircleMore,
  Settings,
  User as UserIcon
} from "lucide-svelte"
import { invalidateAll } from "$app/navigation"
import { Button } from "$lib/components/ui/button/index.js"
import * as DropdownMenu from "$lib/components/ui/dropdown-menu/index.js"
import UserAvatar from "$lib/components/user-avatar.svelte"

let { user } = $props<{
  user: {
    id: string
    name: string
    email: string
    roles: string[]
  }
}>()

const handleLogout = async () => {
  await fetch("/api/auth/logout", { method: "POST" })
  invalidateAll()
  window.location.href = "/"
}

const getDashboardPath = () => {
  if (user.roles.includes("admin")) return "/admin"
  if (user.roles.includes("partner")) return "/partner"
  return "/seller"
}

const getNotificationPath = () => {
  if (user.roles.includes("admin")) return "/admin/notifications"
  if (user.roles.includes("partner")) return "/partner/notifications"
  return "/seller/notifications"
}
</script>

<DropdownMenu.Root>
  <DropdownMenu.Trigger>
    {#snippet child({ props })}
      <Button {...props} variant="ghost" class="relative h-10 w-10 rounded-full p-0">
        <UserAvatar
          name={user.name}
          imageUrl="/avatar.webp"
          class="h-10 w-10"
        />
      </Button>
    {/snippet}
  </DropdownMenu.Trigger>
  <DropdownMenu.Content
    class="w-64 rounded-2xl px-0 py-3"
    align="end"
  >
    <DropdownMenu.Item class="gap-2 rounded-none px-4 py-2.25">
      {#snippet child({ props })}
        <a href={getNotificationPath()} {...props} class="flex w-full items-center gap-2">
          <Bell size="18" strokeWidth="2" />
          <span class="font-medium">Notifications</span>
        </a>
      {/snippet}
    </DropdownMenu.Item>
    
    {#if !user.roles.includes("admin")}
      <DropdownMenu.Item class="gap-2 rounded-none px-4 py-2.25">
        {#snippet child({ props })}
          <a href="/seller/deal-room" {...props} class="flex w-full items-center gap-2">
            <MessageCircleMore size="18" strokeWidth="2" />
            <span class="font-medium">Deal Room</span>
          </a>
        {/snippet}
      </DropdownMenu.Item>
      <DropdownMenu.Item class="gap-2 rounded-none px-4 py-2.25">
        {#snippet child({ props })}
          <a href="/seller/deal-room" {...props} class="flex w-full items-center gap-2">
            <ListChecks size="18" strokeWidth="2" />
            <span class="font-medium">RFQ Hub</span>
          </a>
        {/snippet}
      </DropdownMenu.Item>
      <DropdownMenu.Item class="gap-2 rounded-none px-4 py-2.25">
        {#snippet child({ props })}
          <a href="/seller/deal-room" {...props} class="flex w-full items-center gap-2">
            <Heart size="18" strokeWidth="2" />
            <span class="font-medium">Wishlist</span>
          </a>
        {/snippet}
      </DropdownMenu.Item>
      <DropdownMenu.Item class="gap-2 rounded-none px-4 py-2.25">
        {#snippet child({ props })}
          <a href="/profile" {...props} class="flex w-full items-center gap-2">
            <UserIcon size="18" strokeWidth="2" />
            <span class="font-medium">Profile</span>
          </a>
        {/snippet}
      </DropdownMenu.Item>
    {/if}

    {#if user.roles.includes("partner")}
      <DropdownMenu.Separator />
      <DropdownMenu.Label class="pl-4">Portal</DropdownMenu.Label>
      <DropdownMenu.Item class="gap-2 rounded-none px-4 py-2.25">
        {#snippet child({ props })}
          <a href={getDashboardPath()} {...props} class="flex w-full items-center gap-2">
            <LayoutDashboard size="18" strokeWidth="2" />
            <span class="font-medium">Dashboard</span>
          </a>
        {/snippet}
      </DropdownMenu.Item>

      <DropdownMenu.Item class="gap-2 rounded-none px-4 py-2.25">
        {#snippet child({ props })}
          <a href="/partner/settings" {...props} class="flex w-full items-center gap-2">
            <Settings size="18" strokeWidth="2" />
            <span class="font-medium">Settings</span>
          </a>
        {/snippet}
      </DropdownMenu.Item>
    {/if}

    <DropdownMenu.Separator />
    <DropdownMenu.Item
      onclick={handleLogout}
      class="gap-2 rounded-none px-4 py-2.25 cursor-pointer"
    >
      <span class="font-normal">Log out</span>
    </DropdownMenu.Item>
  </DropdownMenu.Content>
</DropdownMenu.Root>
