// sveltekit-temp/src/lib/components/landing/tx/hero.svelte
<script lang="ts">
import { onDestroy, onMount } from "svelte"
import { getAssetUrl } from "$lib/image-utils.js"
import { cn } from "$lib/utils.js"
import VirtualLobbyDialog from "./virtual-lobby-dialog.svelte"

export interface HeroExpoItem {
  title: string
  dateLabel: string
  slug: string
  detailHref: string
  virtualLobbyUrl?: string
  backgroundImage?: string
}

let { expos }: { expos: HeroExpoItem[] } = $props()

let current = $state(0)
let intervalId: ReturnType<typeof setInterval> | null = null

const activeExpo = $derived(expos[current])
const nextExpo = $derived(expos[(current + 1) % expos.length])

function scrollTo(index: number) {
  current = ((index % expos.length) + expos.length) % expos.length
}

function scrollNext() {
  current = (current + 1) % expos.length
}

onMount(() => {
  intervalId = setInterval(() => {
    scrollNext()
  }, 10000)
})

onDestroy(() => {
  if (intervalId !== null) clearInterval(intervalId)
})
</script>

{#if expos && expos.length > 0}
  <div class="relative min-h-[616px] w-full overflow-hidden">
    <!-- Background Sliding Layer -->
    <div class="absolute inset-0">
      {#each expos as expo, index}
        <div
          class={cn(
            "absolute inset-0 transition-opacity duration-700",
            current === index ? "opacity-100" : "opacity-0"
          )}
        >
          <img
            src={getAssetUrl(expo.backgroundImage, expo.title, 1920, 1080)}
            alt={expo.title}
            class="size-full object-cover"
          />
        </div>
      {/each}
    </div>

    <!-- Static Overlay Layers -->
    <div class="pointer-events-none absolute inset-0">
      <div class="absolute inset-x-0 bottom-0 h-80 bg-gradient-to-b from-black/0 to-black/80 backdrop-blur-[2px]" />

      <div class="container relative mx-auto flex h-full items-end justify-between gap-8 px-5 pb-10 md:pb-14" style="min-height:616px">
        <!-- Main Content - Updates based on activeExpo -->
        <div class="pointer-events-auto max-w-3xl pb-8 text-white">
          <p class="font-medium text-sm drop-shadow-lg transition-all duration-500">
            {activeExpo.dateLabel}
          </p>
          <h1 class="mt-2 max-w-2xl font-medium text-4xl leading-[1.15] tracking-normal drop-shadow-xl transition-all duration-500 md:text-[36px]">
            {activeExpo.title}
          </h1>

          <div class="mt-8 flex flex-wrap gap-4">
            <VirtualLobbyDialog
              src={activeExpo.virtualLobbyUrl}
              expoTitle={activeExpo.title}
            />
            <a
              href={activeExpo.detailHref}
              class="inline-flex h-10 w-44 items-center justify-center rounded-full border border-white bg-white/10 font-medium text-white backdrop-blur hover:bg-white/20 transition"
            >
              View Detail
            </a>
          </div>

          <!-- Pagination Controls -->
          <div class="mt-6 flex items-end gap-4">
            <div class="font-normal text-lg">
              {String(current + 1).padStart(2, "0")}
              <span class="align-baseline text-[10px]">
                /{String(expos.length).padStart(2, "0")}
              </span>
            </div>
            <div class="mb-2 flex items-center gap-1">
              {#each expos as _, i}
                <button
                  type="button"
                  class={cn(
                    "rounded-full transition-all duration-300",
                    current === i
                      ? "h-1.5 w-6 bg-white"
                      : "size-1.5 bg-white/80"
                  )}
                  onclick={() => scrollTo(i)}
                  aria-label={`Go to slide ${i + 1}`}
                ></button>
              {/each}
            </div>
          </div>
        </div>

        <!-- Right Card for the NEXT expo -->
        {#if expos.length > 1}
          <button
            type="button"
            class="pointer-events-auto mb-8 hidden size-56 cursor-pointer overflow-hidden rounded-2xl bg-white p-1 shadow-2xl transition-all duration-500 hover:scale-105 lg:block"
            onclick={scrollNext}
            aria-label={`Next expo: ${nextExpo.title}`}
          >
            <div class="relative h-28 w-full overflow-hidden rounded-xl">
              <img
                src={getAssetUrl(nextExpo.backgroundImage, nextExpo.title, 400, 225)}
                alt=""
                class="size-full object-cover"
              />
            </div>
            <div class="p-2 text-left">
              <p class="font-medium text-[#6b7280] text-xs">
                {nextExpo.dateLabel}
              </p>
              <h2 class="mt-1 line-clamp-2 font-medium text-sm leading-5">
                {nextExpo.title}
              </h2>
            </div>
          </button>
        {/if}
      </div>
    </div>
  </div>
{/if}

// components/landing/tx/hero.tsx
"use client"

import Image from "next/image"
import Link from "next/link"
import * as React from "react"
import { VirtualLobbyDialog } from "@/components/tradexpo/expo-detail/virtual-lobby-dialog"

import {
  Carousel,
  type CarouselApi,
  CarouselContent,
  CarouselItem
} from "@/components/ui/carousel"
import { getAssetUrl } from "@/lib/image-utils"
import { cn } from "@/lib/utils"

export interface HeroExpoItem {
  title: string
  dateLabel: string
  slug: string
  detailHref: string
  actionHref?: string
  virtualLobbyUrl?: string
  backgroundImage?: string
}

export interface HeroProps {
  expos: HeroExpoItem[]
}

export function Hero({ expos }: HeroProps) {
  const [api, setApi] = React.useState<CarouselApi>()
  const [current, setCurrent] = React.useState(0)

  React.useEffect(() => {
    if (!api) return

    setCurrent(api.selectedScrollSnap())

    const onSelect = () => {
      setCurrent(api.selectedScrollSnap())
    }

    api.on("select", onSelect)

    // Auto slide every 10 seconds
    const intervalId = setInterval(() => {
      api.scrollNext()
    }, 10000)

    return () => {
      api.off("select", onSelect)
      clearInterval(intervalId)
    }
  }, [api])

  if (!expos || expos.length === 0) return null

  const activeExpo = expos[current]
  const nextExpo = expos[(current + 1) % expos.length]

  return (
    <div className="relative min-h-154 w-full overflow-hidden">
      {/* Background Sliding Layer */}
      <Carousel
        setApi={setApi}
        className="absolute inset-0 size-full"
        opts={{ loop: true }}
      >
        <CarouselContent className="ml-0 h-154">
          {expos.map((expo, index) => (
            <CarouselItem key={expo.slug} className="relative pl-0">
              <div className="relative size-full">
                <Image
                  src={getAssetUrl(
                    expo.backgroundImage,
                    expo.title,
                    1920,
                    1080
                  )}
                  alt={expo.title}
                  fill
                  priority={index === 0}
                  sizes="100vw"
                  className="object-cover"
                />
              </div>
            </CarouselItem>
          ))}
        </CarouselContent>
      </Carousel>

      {/* Static Overlay Layers */}
      <div className="pointer-events-none absolute inset-0">
        <div className="absolute inset-x-0 bottom-0 h-80 bg-linear-to-b from-black/0 to-black/80 backdrop-blur-[2px]" />

        <div className="container relative mx-auto flex h-full items-end justify-between gap-8 px-5 pb-10 md:pb-14">
          {/* Main Content - Updates based on activeExpo */}
          <div className="pointer-events-auto max-w-3xl pb-8 text-white">
            <p className="font-medium text-sm drop-shadow-lg transition-all duration-500">
              {activeExpo.dateLabel}
            </p>
            <h1 className="mt-2 max-w-2xl font-medium text-4xl leading-[1.15] tracking-normal drop-shadow-xl transition-all duration-500 md:text-[36px]">
              {activeExpo.title}
            </h1>

            <div className="mt-8 flex flex-wrap gap-4">
              <VirtualLobbyDialog
                src={activeExpo.virtualLobbyUrl}
                expoTitle={activeExpo.title}
              />
              <Link
                href={activeExpo.detailHref}
                className="inline-flex h-10 w-44 items-center justify-center rounded-full border border-white bg-white/10 font-medium text-white backdrop-blur"
              >
                View Detail
              </Link>
            </div>

            {/* Pagination Controls */}
            <div className="mt-6 flex items-end gap-4">
              <div className="font-normal text-lg">
                {String(current + 1).padStart(2, "0")}
                <span className="align-baseline text-[10px]">
                  /{String(expos.length).padStart(2, "0")}
                </span>
              </div>
              <div className="mb-2 flex items-center gap-1">
                {expos.map((_, i) => (
                  <button
                    type="button"
                    key={`hero-dot-${expos[i].slug}`}
                    className={cn(
                      "rounded-full transition-all duration-300",
                      current === i
                        ? "h-1.5 w-6 bg-white"
                        : "size-1.5 bg-white/80"
                    )}
                    onClick={() => api?.scrollTo(i)}
                    aria-label={`Go to slide ${i + 1}`}
                  />
                ))}
              </div>
            </div>
          </div>

          {/* Right Card for the NEXT expo */}
          {expos.length > 1 && (
            <article
              className="pointer-events-auto mb-8 hidden size-56 cursor-pointer overflow-hidden rounded-2xl bg-white p-1 shadow-2xl transition-all duration-500 hover:scale-105 lg:block"
              onClick={() => api?.scrollNext()}
              onKeyDown={(e) => {
                if (e.key === "Enter" || e.key === " ") {
                  e.preventDefault()
                  api?.scrollNext()
                }
              }}
              aria-label={`Next expo: ${nextExpo.title}`}
            >
              <div className="relative h-28 w-full overflow-hidden rounded-xl">
                <Image
                  src={getAssetUrl(
                    nextExpo.backgroundImage,
                    nextExpo.title,
                    400,
                    225
                  )}
                  alt=""
                  fill
                  className="object-cover"
                />
              </div>
              <div className="p-2">
                <p className="font-medium text-[#6b7280] text-xs">
                  {nextExpo.dateLabel}
                </p>
                <h2 className="mt-1 line-clamp-2 font-medium text-sm leading-5">
                  {nextExpo.title}
                </h2>
              </div>
            </article>
          )}
        </div>
      </div>
    </div>
  )
}
