// sveltekit-temp/src/lib/components/landing/login-link.svelte
<script lang="ts">
import { page } from "$app/stores"
import { Button } from "$lib/components/ui/button/index.js"

let loginUrl = $derived.by(() => {
  const pathname = $page.url.pathname
  return pathname === "/login"
    ? "/login"
    : `/login?callbackUrl=${encodeURIComponent(pathname)}`
})
</script>

<a href={loginUrl}>
  <Button variant="ghost" class="font-medium">
    Login or Sign up
  </Button>
</a>

// components/landing/login-link.tsx
"use client"

import Link from "next/link"
import { usePathname } from "next/navigation"
import { Button } from "../ui/button"

export function LoginLink() {
  const pathname = usePathname()
  const loginUrl =
    pathname === "/login"
      ? "/login"
      : `/login?callbackUrl=${encodeURIComponent(pathname)}`

  return (
    <Link href={loginUrl}>
      <Button variant="ghost" className="font-medium">
        Login or Sign up
      </Button>
    </Link>
  )
}
